language: java

jdk:
  - openjdk11
  
stages:
 # - continousIntegration
  - continousDelivery

before_install:
  - chmod +x gradlew
  - nvm install 0.10
  
install:
  - npm install -g newman
  
before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
   
addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN
    
jobs:
  include:
  #  - stage: continousIntegration
  #    script: ./gradlew sonarqube
    - stage: continousDelivery
      deploy:
        provider: heroku
        api-key: $HEROKU_API_KEY
        app: $HEROKU_STAGING_APP
      after_success:
      script: npm --version
      script: node_modules/.bin/newman run src/test/java/systemtests/collection/CRUD.postman_collection.json -e src/test/java/systemtests/uek223advancedenv.postman_environment.json

