jdk:
  - openjdk11
  
stages:
  - unitTestsAndIntegrationTests
  - continousDelivery
  
before_install:
  - chmod +x gradlew
  
#install:
#  - npm install newman
    
jobs:
  include:
#    - stage: unitTestsAndIntegrationTests
#      script: ./gradlew test 
    - stage: continousDelivery
      deploy:
        provider: heroku
        api-key: $HEROKU_API_KEY
        app: uek223staging
